// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBJTryrJ2wB1JKLsxefd_UwA75F4U_LAA',
    appId: '1:391374188692:web:68ed583eff0529ca710481',
    messagingSenderId: '391374188692',
    projectId: 'edumind-cd737',
    authDomain: 'edumind-cd737.firebaseapp.com',
    storageBucket: 'edumind-cd737.firebasestorage.app',
    measurementId: 'G-3P9X5CJ93Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5TUd9GGoBu_Cj2hXYr_eNV4MQaO_I8kU',
    appId: '1:391374188692:android:6728f1c37f929db0710481',
    messagingSenderId: '391374188692',
    projectId: 'edumind-cd737',
    storageBucket: 'edumind-cd737.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApTljS3rErDInD6IvGRoGPRP4RxJeBkz0',
    appId: '1:391374188692:ios:3cb5735a0839c9b7710481',
    messagingSenderId: '391374188692',
    projectId: 'edumind-cd737',
    storageBucket: 'edumind-cd737.firebasestorage.app',
    iosBundleId: 'com.example.edumind',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApTljS3rErDInD6IvGRoGPRP4RxJeBkz0',
    appId: '1:391374188692:ios:3cb5735a0839c9b7710481',
    messagingSenderId: '391374188692',
    projectId: 'edumind-cd737',
    storageBucket: 'edumind-cd737.firebasestorage.app',
    iosBundleId: 'com.example.edumind',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBJTryrJ2wB1JKLsxefd_UwA75F4U_LAA',
    appId: '1:391374188692:web:e319a5a50f93ae03710481',
    messagingSenderId: '391374188692',
    projectId: 'edumind-cd737',
    authDomain: 'edumind-cd737.firebaseapp.com',
    storageBucket: 'edumind-cd737.firebasestorage.app',
    measurementId: 'G-WMXT9E36SK',
  );
}
